#!/usr/bin/env node

const fs      = require('fs')
const babel   = require('babel-core')
const convert = require('../src/index')

const files = fs.readdirSync('./src')

files.forEach((fileName) => {

  // read the code from this file
  fs.readFile(`./src/${fileName}`, (err, data) => {
    if (err) throw err

    // convert from a buffer to a string
    let src = data.toString()

    // use our plugin to transform the source
    let out = babel.transform(src, { plugins: [convert] })

    if (fileName === 'one.js') {
      let r = fs.readFileSync('./dist/one.js', 'utf8')
      if (r.trim() === out.code) {
        console.log('Test 1 Passed.')
      } else {
        console.log('Test 1 Failed')
      }
    }

    if (fileName === 'two.js') {
      let r = fs.readFileSync('./dist/two.js', 'utf8')
      if (r.trim() === out.code) {
        console.log('Test 2 Passed.')
      } else {
        console.log('Test 2 Failed')
      }
    }

  })

})
